-- 1. Ensure the user exists
INSERT INTO users (username, password_hash) 
VALUES ('admin', 'password') 
ON CONFLICT (username) DO NOTHING;

-- 2. Create rooms table if it wasn't generated by Hibernate
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    target_temperature DOUBLE PRECISION DEFAULT 23.0
);

-- 3. Insert some mock data for the smart home frontend to display
INSERT INTO rooms (name, target_temperature) VALUES ('Living Room', 22.5);
INSERT INTO rooms (name, target_temperature) VALUES ('Bedroom', 21.0);