networks:
  smart_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:

services:
  # --- 1. Relational Database ---
  db_relational:
    image: postgres:16-alpine
    container_name: smart_postgres
    restart: unless-stopped
    networks:
      - smart_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: smart_password
      POSTGRES_DB: smart_home_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smart_home_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  # --- 2. NoSQL Database ---
  db_nosql:
    image: mongo:7-jammy
    container_name: smart_mongo
    restart: unless-stopped
    networks:
      - smart_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 3s
      retries: 5

  # --- 3. MQTT Broker ---
  broker:
    image: eclipse-mosquitto:2.0
    container_name: smart_mqtt
    restart: unless-stopped
    networks:
      - smart_network
    ports:
      - "1883:1883"
    entrypoint:
      [
        "sh",
        "-c",
        "echo 'listener 1883\nallow_anonymous true' > /tmp/mosquitto.conf && exec mosquitto -c /tmp/mosquitto.conf",
      ]
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 1883 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5

  # --- 4. Go Backend Service ---
  backend_go:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart_go
    restart: unless-stopped
    networks:
      - smart_network
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Tallinn
      - PORT=8080
      - POSTGRES_URL=postgresql://admin:smart_password@db_relational:5432/smart_home_db?sslmode=disable
      - MONGO_URI=mongodb://db_nosql:27017
      - MQTT_BROKER=tcp://broker:1883
      - GO_BACKEND_URL=http://backend_go:8080/api/v1/telemetry
      - JWT_SECRET=super_secret_smart_home_jwt_key_2026
    depends_on:
      db_relational:
        condition: service_healthy
      db_nosql:
        condition: service_healthy
      broker:
        condition: service_healthy
